# Información del Sitio
title: "IS-FUNDAMENTOS"
description: "Centro de Unidades de Aprendizaje - Monitoría DOPO/MYSD"
baseurl: "/software-foundations-eci" # Nombre del repo
url: "https://anderssonprogramming.github.io"

# 💎 EL MEJOR TEMA: Just the Docs
remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

# Configuración del Tema
search_enabled: true
heading_anchors: true
aux_links:
  "GitHub Repository":
    - "https://github.com/anderssonprogramming/software-foundations-eci"
aux_links_new_tab: true

# Navegación
nav_fold: false
